# Generated by Django 5.2.6 on 2025-09-22 07:38

import django.db.models.deletion
import tx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx', '0004_event_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tx.models.attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tx.event')),
            ],
        ),
    ]
