# Generated by Django 5.2.6 on 2025-09-28 05:19

import django.db.models.deletion
import tx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tx", "0005_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.IntegerField(help_text="Numerical identifier for the account"),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                help_text="Descriptive name of the account", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this attachment was uploaded",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="event",
            field=models.ForeignKey(
                help_text="The event this attachment is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tx.event",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                help_text="Uploaded file attachment (renamed with UUID)",
                upload_to=tx.models.attachment_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this event was created in the system",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(
                help_text="The date when this accounting event occurred"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                help_text="Brief description of the accounting event", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional financial year this event belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="tx.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="financialyear",
            name="end_date",
            field=models.DateField(help_text="The last day of the financial year"),
        ),
        migrations.AlterField(
            model_name="financialyear",
            name="start_date",
            field=models.DateField(help_text="The first day of the financial year"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                help_text="The account this transaction affects",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="tx.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Transaction amount with up to 12 digits and 2 decimal places",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="direction",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")],
                help_text="Whether this is a debit or credit transaction",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="event",
            field=models.ForeignKey(
                help_text="The event this transaction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="tx.event",
            ),
        ),
    ]
