# Generated by Django 5.2.6 on 2025-09-28 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tx", "0006_alter_account_code_alter_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="financial_year",
            field=models.ForeignKey(
                help_text="Optional financial year this event belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="tx.financialyear",
            ),
        ),
    ]
